name: Process New Event

on:
  push:
    branches:
      - main
    paths:
      - 'content/events/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for "Create Pull Request" step

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd ai && yarn install --network-timeout 1000000

      - name: Build and Process new event
        run: cd ai && yarn start
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Set up Git user
        run: |
          git config --local user.email "niteshbalusu@icloud.com"
          git config --local user.name "Nitesh Balusu"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: '🧠 New AI generated summary'
          commit-message: Add summary
          body: 'This pull request adds a new summary file. This PR was opened automatically by a GitHub Action and the summary was generated by a LLM. Please give the summaries human review before merging!'
          branch: 'new-summary'
